### ISSUE TITLE
Team up

### ISSUE THREAD

**Issue by AmauryVanEspen** [TinhToQuang/Devtoberfest2021-ABAP_RAP_App#1]
hi @TinhToQuang 
would you be interested in team up on this RESTful open source project ?
https://github.com/AmauryVanEspen/OpenSAP-certification-API
Regards
Amaury

**Comment by TinhToQuang** [comment]
Hi @AmauryVanEspen,
Yes. I'm interested.
Regards,
Tinh

**Comment by AmauryVanEspen** [comment]
HI @TinhToQuang 
let's contact me through https://people.sap.com/amauryvanespen (follow then message), gonna share my email, or contact me through linkedin. I'm setting up the project.
Regards
Amaury

**Comment by TinhToQuang** [comment]
> HI @TinhToQuang let's contact me through https://people.sap.com/amauryvanespen (follow then message), gonna share my email, or contact me through linkedin. I'm setting up the project. Regards Amaury

Hi Amaury,
I have just added you through Linkedin and share my Github profile.
We can contact together through Linkedin or email: toquangtinh at gmail dot com
